AWSTemplateFormatVersion: 2010-09-09
Parameters:
  S3Bucket:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: 'S3Bucket-TripService'
  S3Key:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: 'S3Key-TripService'
Resources:
  #Database
  Greetings:
    Type: 'AWS::DynamoDB::Table'
    Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: !Sub '${AWS::StackName}-Greetings-Table'
  #Ploicy
  GreetingDynamoDbWriterPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    DependsOn: "Greeting"
    Properties:
      Description: "Write Policy for accessing Trip Service Dyanmo DB Tables"
      ManagedPolicyName: !Sub "FordApp-${AWS::StackName}-DynamoDbWriter-Policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - 'dynamodb:BatchWrite*'
              - 'dynamodb:Delete*'
              - 'dynamodb:Update*'
              - 'dynamodb:PutItem'
            Resource: !GetAtt Greetings.Arn
    #Roles
  SaveGreetingLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "FordApp-${AWS::StackName}-SaveGreeting-Role"
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/FordDevelopmentPolicyBoundary'
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - !Ref GreetingDynamoDbWriterPolicy

  #Lambdas
  SaveGreetingLambda:
    Description: POC for GraalVM
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Join [ "", [!Ref S3Key, "TripService.zip" ] ]
      FunctionName: !Sub '${AWS::StackName}-SaveGreeting-Lambda'
      Handler: 'com.github.md.Handler'
      Runtime: provided
      Role: !GetAtt SaveGreetingLambdaRole.Arn
      Timeout: 60
      MemorySize: 512
      TracingConfig:
        Mode: Active
      Environment:
        Variables:
          greetings: !Ref Greetings
          Region: !Sub "${AWS::Region}"